FROM tianon/docker-tianon

ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

WORKDIR $GOPATH/src/kubecon-demo

COPY *.go ./
RUN set -eux; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		golang-go \
	; \
	rm -rf /var/lib/apt/lists/*; \
	\
	go install -v ./...; \
	\
	apt-mark auto '.*' > /dev/null; \
	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
	apt-get purge -y --auto-remove

COPY static static

CMD ["kubecon-demo"]
